### ISSUE TITLE
usbip is required for WSL to attach usb devices

### ISSUE THREAD

**Issue by 666threesixes666** [funtoo/macaroni-funtoo#55]
im requesting usbip be bumped/autogen to a more recent linux kernel.  i adjusted a gentoo usbip bumped it to 6.9 and got that to install fine.  posted the template to funtoo's bug tracker.  don't know if that's going to be showing up.  this is also required to use usb devices over the network.

**Comment by geaaru** [comment]
@666threesixes666 if this issue is related to the MARK stack please open an issue in `mark-issues` repo. This repo is for the issues related to the Macaroni binary stack.
Btw, do you mean the tool `net-misc/usbip`? or a specific kernel module? Just to fix this on Macaroni binary stack too.
